# Generated by Django 4.1.1 on 2022-09-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anexos_sip', '0006_sip_buddies_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sip_buddies',
            name='telefono',
        ),
    ]
