# Generated by Django 4.1.1 on 2022-09-22 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sip_telefono', '0005_remove_sip_telefono_telefono'),
        ('anexos_sip', '0007_remove_sip_buddies_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='sip_buddies',
            name='telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefono', to='sip_telefono.sip_telefono'),
        ),
    ]
