# Generated by Django 4.1.1 on 2022-09-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marca_telefono',
            fields=[
                ('id_marca_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('no_marca_telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('il_activo', models.BooleanField(blank=True, default=True, null=True)),
                ('il_formato_mac', models.IntegerField(blank=True, default=0, null=True)),
                ('il_need_mac_for_provisioning', models.BooleanField(blank=True, default=False, null=True)),
                ('no_extension_for_provisioning', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'tc_marca',
            },
        ),
        migrations.CreateModel(
            name='modelo_telefono',
            fields=[
                ('id_modelo_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('no_modelo_telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('il_activo', models.BooleanField(blank=True, default=True, null=True)),
                ('id_marca_telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sip_telefono.marca_telefono')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelo',
                'db_table': 'tc_modelo',
            },
        ),
        migrations.CreateModel(
            name='sip_telefono',
            fields=[
                ('id_sip_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario_sip', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('no_mac', models.CharField(blank=True, max_length=100, null=True)),
                ('no_ip_dominio', models.CharField(blank=True, max_length=50, null=True)),
                ('no_ruta', models.CharField(blank=True, max_length=200, null=True)),
                ('id_marca_telefono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sip_telefono.marca_telefono')),
                ('id_modelo_telefono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sip_telefono.modelo_telefono')),
            ],
            options={
                'verbose_name': 'Telefono',
                'verbose_name_plural': 'Telefonos',
                'db_table': 'tb_sip_telefono',
            },
        ),
    ]
